[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "common"
version = "0.1.0"
description = "Shared models, utilities, and policies for Healthcare Support Portal"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "sqlalchemy>=2.0.0",
    "oso>=0.27.0",
    "sqlalchemy-oso>=0.9.0",
    "pydantic>=2.0.0",
    "passlib[bcrypt]>=1.7.4",
    "python-jose[cryptography]>=3.3.0",
    "pgvector>=0.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/common"]

[tool.hatch.build]
include = ["src/common"]